<?php
$pageTitle='Events';require_once __DIR__.'/../includes/auth.php';requireAdmin();$db=getDB();
if(isset($_GET['delete'])&&verifyCsrf()){$db->prepare("DELETE FROM events WHERE id=?")->execute([(int)$_GET['delete']]);auditLog('delete_event','event',(int)$_GET['delete']);setFlash('success','Deleted.');header('Location: /admin/events.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf()){$eid=(int)($_POST['event_id']??0);$d=[trim($_POST['title']??''),trim($_POST['description']??''),$_POST['event_date']??'',$_POST['end_date']?:null,$_POST['event_time']?:null,trim($_POST['location']??''),$_POST['type']??'other',isset($_POST['is_public'])?1:0];if(!$d[0]||!$d[2])setFlash('error','Title and date required.');else{if($eid){$db->prepare("UPDATE events SET title=?,description=?,event_date=?,end_date=?,event_time=?,location=?,type=?,is_public=? WHERE id=?")->execute([...$d,$eid]);auditLog('update_event','event',$eid);}else{$db->prepare("INSERT INTO events (title,description,event_date,end_date,event_time,location,type,is_public,created_by) VALUES (?,?,?,?,?,?,?,?,?)")->execute([...$d,currentUserId()]);auditLog('create_event','event',(int)$db->lastInsertId());}setFlash('success','Saved.');}header('Location: /admin/events.php');exit;}
$editEvent=null;if(isset($_GET['edit'])){$stmt=$db->prepare("SELECT * FROM events WHERE id=?");$stmt->execute([(int)$_GET['edit']]);$editEvent=$stmt->fetch();}
$events=$db->query("SELECT * FROM events ORDER BY event_date DESC")->fetchAll();require_once __DIR__.'/../includes/header.php';$ev=$editEvent??[];?>
<div class="row g-3"><div class="col-lg-5"><div class="card border-0 rounded-3"><div class="card-header bg-white border-0"><h6 class="fw-semibold mb-0"><?=$editEvent?'Edit':'Add'?> Event</h6></div><div class="card-body"><form method="POST"><?=csrfField()?><input type="hidden" name="event_id" value="<?=$ev['id']??0?>">
<div class="mb-2"><label class="form-label">Title *</label><input type="text" name="title" class="form-control form-control-sm" required value="<?=e($ev['title']??'')?>"></div>
<div class="row g-2 mb-2"><div class="col-6"><label class="form-label">Date *</label><input type="date" name="event_date" class="form-control form-control-sm" required value="<?=e($ev['event_date']??'')?>"></div><div class="col-6"><label class="form-label">End Date</label><input type="date" name="end_date" class="form-control form-control-sm" value="<?=e($ev['end_date']??'')?>"></div></div>
<div class="row g-2 mb-2"><div class="col-6"><label class="form-label">Time</label><input type="time" name="event_time" class="form-control form-control-sm" value="<?=e($ev['event_time']??'')?>"></div><div class="col-6"><label class="form-label">Type</label><select name="type" class="form-select form-select-sm"><?php foreach(['academic','cultural','sports','holiday','exam','meeting','other'] as $t):?><option value="<?=$t?>" <?=($ev['type']??'')===$t?'selected':''?>><?=ucfirst($t)?></option><?php endforeach;?></select></div></div>
<div class="mb-2"><label class="form-label">Location</label><input type="text" name="location" class="form-control form-control-sm" value="<?=e($ev['location']??'')?>"></div>
<div class="mb-2"><label class="form-label">Description</label><textarea name="description" class="form-control form-control-sm" rows="2"><?=e($ev['description']??'')?></textarea></div>
<div class="form-check mb-3"><input type="checkbox" name="is_public" class="form-check-input" <?=($ev['is_public']??1)?'checked':''?>><label class="form-check-label">Public</label></div>
<button class="btn btn-primary btn-sm"><?=$editEvent?'Update':'Add'?></button><?php if($editEvent):?> <a href="/admin/events.php" class="btn btn-outline-secondary btn-sm">Cancel</a><?php endif;?></form></div></div></div>
<div class="col-lg-7"><div class="card border-0 rounded-3"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Title</th><th>Date</th><th>Type</th><th>Actions</th></tr></thead><tbody>
<?php foreach($events as $ev):?><tr><td style="font-size:.85rem"><?=e($ev['title'])?></td><td style="font-size:.85rem"><?=date('M d, Y',strtotime($ev['event_date']))?></td><td><span class="badge bg-light text-dark"><?=e($ev['type'])?></span></td><td><a href="/admin/events.php?edit=<?=$ev['id']?>" class="btn btn-sm btn-outline-primary py-0 px-2"><i class="bi bi-pencil"></i></a> <a href="/admin/events.php?delete=<?=$ev['id']?>&csrf_token=<?=csrfToken()?>" class="btn btn-sm btn-outline-danger py-0 px-2" onclick="return confirm('Delete?')"><i class="bi bi-trash"></i></a></td></tr><?php endforeach;?></tbody></table></div></div></div></div></div>
<?php require_once __DIR__.'/../includes/footer.php';?>
