<?php
$pageTitle='Gallery';require_once __DIR__.'/../includes/auth.php';requireAdmin();$db=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf()){$gid=(int)($_POST['id']??0);$action=$_POST['action']??'';if($gid&&in_array($action,['approved','rejected','delete'])){if($action==='delete')$db->prepare("DELETE FROM gallery_items WHERE id=?")->execute([$gid]);else $db->prepare("UPDATE gallery_items SET status=?,approved_by=?,approved_at=NOW() WHERE id=?")->execute([$action,currentUserId(),$gid]);auditLog("gallery_$action",'gallery',$gid);setFlash('success','Done.');}header('Location: /admin/gallery.php');exit;}
$statusFilter=$_GET['status']??'pending';$where=$statusFilter?"WHERE g.status=?":"";$params=$statusFilter?[$statusFilter]:[];
$stmt=$db->prepare("SELECT g.*,u.name as uploader_name FROM gallery_items g LEFT JOIN users u ON g.uploaded_by=u.id $where ORDER BY g.created_at DESC");$stmt->execute($params);$items=$stmt->fetchAll();
require_once __DIR__.'/../includes/header.php';?>
<ul class="nav nav-pills mb-3"><?php foreach(['pending'=>'warning','approved'=>'success','rejected'=>'danger',''=>'secondary'] as $s=>$c):?><li class="nav-item"><a href="/admin/gallery.php?status=<?=$s?>" class="nav-link <?=$statusFilter===$s?'active':''?> btn-sm"><?=$s?ucfirst($s):'All'?></a></li><?php endforeach;?></ul>
<div class="row g-3"><?php if(empty($items)):?><div class="col-12"><div class="card border-0 rounded-3"><div class="card-body text-center text-muted py-5">No items</div></div></div>
<?php else:foreach($items as $g):?><div class="col-6 col-md-4 col-lg-3"><div class="card border-0 rounded-3 h-100"><img src="<?=e($g['file_path'])?>" class="card-img-top" style="height:160px;object-fit:cover;border-radius:12px 12px 0 0"><div class="card-body p-2"><h6 class="mb-1" style="font-size:.85rem"><?=e($g['title'])?></h6><small class="text-muted"><?=e($g['uploader_name']??'?')?> · <?=e($g['category'])?></small><div class="mt-2 d-flex gap-1">
<?php if($g['status']==='pending'):?><form method="POST"><input type="hidden" name="id" value="<?=$g['id']?>"><input type="hidden" name="action" value="approved"><?=csrfField()?><button class="btn btn-sm btn-success py-0 px-2"><i class="bi bi-check"></i></button></form><form method="POST"><input type="hidden" name="id" value="<?=$g['id']?>"><input type="hidden" name="action" value="rejected"><?=csrfField()?><button class="btn btn-sm btn-danger py-0 px-2"><i class="bi bi-x"></i></button></form><?php endif;?>
<form method="POST"><input type="hidden" name="id" value="<?=$g['id']?>"><input type="hidden" name="action" value="delete"><?=csrfField()?><button class="btn btn-sm btn-outline-secondary py-0 px-2" onclick="return confirm('Delete?')"><i class="bi bi-trash"></i></button></form></div></div></div></div>
<?php endforeach;endif;?></div>
<?php require_once __DIR__.'/../includes/footer.php';?>
