<?php
$pageTitle='Notifications';require_once __DIR__.'/../includes/auth.php';requireAdmin();$db=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf()){$nid=(int)($_POST['id']??0);$action=$_POST['action']??'';if($nid&&in_array($action,['approved','rejected','delete'])){if($action==='delete'){$db->prepare("DELETE FROM notifications WHERE id=?")->execute([$nid]);auditLog('delete_notification','notification',$nid);}else{$db->prepare("UPDATE notifications SET status=?,approved_by=?,approved_at=NOW(),is_public=? WHERE id=?")->execute([$action,currentUserId(),$action==='approved'?1:0,$nid]);auditLog("notification_$action",'notification',$nid);}setFlash('success','Done.');}header('Location: /admin/notifications.php');exit;}
$statusFilter=$_GET['status']??'pending';$where=$statusFilter?"WHERE n.status=?":"";$params=$statusFilter?[$statusFilter]:[];
$stmt=$db->prepare("SELECT n.*,u.name as poster_name FROM notifications n LEFT JOIN users u ON n.posted_by=u.id $where ORDER BY n.created_at DESC");$stmt->execute($params);$notifications=$stmt->fetchAll();
require_once __DIR__.'/../includes/header.php';?>
<ul class="nav nav-pills mb-3"><?php foreach(['pending'=>'warning','approved'=>'success','rejected'=>'danger',''=>'secondary'] as $s=>$c):?><li class="nav-item"><a href="/admin/notifications.php?status=<?=$s?>" class="nav-link <?=$statusFilter===$s?'active':''?> btn-sm"><?=$s?ucfirst($s):'All'?></a></li><?php endforeach;?></ul>
<div class="card border-0 rounded-3"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Title</th><th>Type</th><th>By</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>
<?php if(empty($notifications)):?><tr><td colspan="6" class="text-center text-muted py-4">None</td></tr>
<?php else:foreach($notifications as $n):?><tr><td style="font-size:.85rem;max-width:250px" class="text-truncate"><?=e($n['title'])?></td><td><span class="badge bg-light text-dark"><?=e($n['type'])?></span></td><td style="font-size:.85rem"><?=e($n['poster_name']??'System')?></td><td><?php $c=['pending'=>'warning','approved'=>'success','rejected'=>'danger'];?><span class="badge bg-<?=$c[$n['status']]?>-subtle text-<?=$c[$n['status']]?>"><?=ucfirst($n['status'])?></span></td><td style="font-size:.8rem"><?=date('M d',strtotime($n['created_at']))?></td><td>
<?php if($n['status']==='pending'):?><form method="POST" class="d-inline"><input type="hidden" name="id" value="<?=$n['id']?>"><input type="hidden" name="action" value="approved"><?=csrfField()?><button class="btn btn-sm btn-outline-success py-0 px-2"><i class="bi bi-check-lg"></i></button></form><form method="POST" class="d-inline"><input type="hidden" name="id" value="<?=$n['id']?>"><input type="hidden" name="action" value="rejected"><?=csrfField()?><button class="btn btn-sm btn-outline-danger py-0 px-2"><i class="bi bi-x-lg"></i></button></form><?php endif;?>
<form method="POST" class="d-inline"><input type="hidden" name="id" value="<?=$n['id']?>"><input type="hidden" name="action" value="delete"><?=csrfField()?><button class="btn btn-sm btn-outline-secondary py-0 px-2" onclick="return confirm('Delete?')"><i class="bi bi-trash"></i></button></form></td></tr>
<?php endforeach;endif;?></tbody></table></div></div></div>
<?php require_once __DIR__.'/../includes/footer.php';?>
